SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP DATABASE IF EXISTS SUPERMARKETDB;
CREATE SCHEMA IF NOT EXISTS `SUPERMARKETDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `SUPERMARKETDB` ;

-- -----------------------------------------------------
-- Table `SUPERMARKETDB`.`USER`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `SUPERMARKETDB`.`USER` (
  `USER_ID` VARCHAR(45) NOT NULL COMMENT '编号' ,
  `USER_NAME` VARCHAR(45) NOT NULL COMMENT '姓名' ,
  `USER_PASSWD` VARCHAR(45) NOT NULL COMMENT '密码' ,
  `USER_TYPE` VARCHAR(45) NOT NULL COMMENT '类型' ,
  PRIMARY KEY (`USER_ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '用户';


-- -----------------------------------------------------
-- Table `SUPERMARKETDB`.`WAREHOUSE`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `SUPERMARKETDB`.`WAREHOUSE` (
  `WAREHOUSE_ID` VARCHAR(45) NOT NULL COMMENT '仓库ID' ,
  `WAREHOUSE_SIZE` INT NOT NULL COMMENT '容量 ' ,
  `WAREHOUSE_LOCATION` VARCHAR(45) NOT NULL COMMENT '位置' ,
  PRIMARY KEY (`WAREHOUSE_ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '仓库';


-- -----------------------------------------------------
-- Table `SUPERMARKETDB`.`GOODS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `SUPERMARKETDB`.`GOODS` (
  `GOODS_ID` VARCHAR(45) NOT NULL COMMENT '货物ID' ,
  `GOODS_BATCH` VARCHAR(45) NOT NULL COMMENT '批次' ,
  `WAREHOUSE_ID` VARCHAR(45) NOT NULL COMMENT '仓库编号' ,
  `GOODS_NAME` VARCHAR(45) NOT NULL COMMENT '货物名' ,
  `NUM` INT NOT NULL COMMENT '数目' ,
  PRIMARY KEY (`GOODS_ID`, `GOODS_BATCH`, `WAREHOUSE_ID`) ,
  INDEX `fk_GOODS_WAREHOUSE1_idx` (`WAREHOUSE_ID` ASC) ,
  CONSTRAINT `fk_GOODS_WAREHOUSE1`
    FOREIGN KEY (`WAREHOUSE_ID` )
    REFERENCES `SUPERMARKETDB`.`WAREHOUSE` (`WAREHOUSE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '货物';


-- -----------------------------------------------------
-- Table `SUPERMARKETDB`.`WAREHOUSE_USER_MAINTAIN`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `SUPERMARKETDB`.`WAREHOUSE_USER_MAINTAIN` (
  `WAREHOUSE_ID` VARCHAR(45) NOT NULL COMMENT '仓库ID' ,
  `USER_ID` VARCHAR(45) NOT NULL COMMENT '用户ID' ,
  PRIMARY KEY (`WAREHOUSE_ID`, `USER_ID`) ,
  INDEX `fk_WAREHOUSE_has_USER_USER1_idx` (`USER_ID` ASC) ,
  INDEX `fk_WAREHOUSE_has_USER_WAREHOUSE1_idx` (`WAREHOUSE_ID` ASC) ,
  CONSTRAINT `fk_WAREHOUSE_has_USER_WAREHOUSE1`
    FOREIGN KEY (`WAREHOUSE_ID` )
    REFERENCES `SUPERMARKETDB`.`WAREHOUSE` (`WAREHOUSE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WAREHOUSE_has_USER_USER1`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `SUPERMARKETDB`.`USER` (`USER_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '用户能访问的仓库';


-- -----------------------------------------------------
-- Table `SUPERMARKETDB`.`WAREHOUSE_RECORD`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `SUPERMARKETDB`.`WAREHOUSE_RECORD` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '序号' ,
  `GOODS_ID` VARCHAR(45) NOT NULL COMMENT '货物编号' ,
  `GOODS_BATCH` VARCHAR(45) NOT NULL COMMENT '货物批次' ,
  `WAREHOUSE_ID` VARCHAR(45) NOT NULL COMMENT '仓库编号' ,
  `USER_ID` VARCHAR(45) NOT NULL COMMENT '操作者' ,
  `DATETIME` DATETIME NOT NULL COMMENT '操作时间' ,
  `TYPE` VARCHAR(45) NOT NULL COMMENT '操作类型' ,
  `NUM` INT NOT NULL COMMENT '数目' ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_WAREHOUSE_has_GOODS_GOODS2_idx` (`GOODS_ID` ASC, `GOODS_BATCH` ASC) ,
  INDEX `fk_WAREHOUSE_has_GOODS_WAREHOUSE1_idx` (`WAREHOUSE_ID` ASC) ,
  INDEX `fk_WAREHOUSE_RECORD_USER1_idx` (`USER_ID` ASC) ,
  CONSTRAINT `fk_WAREHOUSE_has_GOODS_WAREHOUSE1`
    FOREIGN KEY (`WAREHOUSE_ID` )
    REFERENCES `SUPERMARKETDB`.`WAREHOUSE` (`WAREHOUSE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WAREHOUSE_has_GOODS_GOODS2`
    FOREIGN KEY (`GOODS_ID` , `GOODS_BATCH` )
    REFERENCES `SUPERMARKETDB`.`GOODS` (`GOODS_ID` , `GOODS_BATCH` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WAREHOUSE_RECORD_USER1`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `SUPERMARKETDB`.`USER` (`USER_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '仓库操作记录';

USE `SUPERMARKETDB` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
